import Head from 'next/head'
import CallToAction from '../components/CallToAction/CallToAction'
import Header from '../components/Header/Header'
import { Layout } from '../layout/Layout'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <CallToAction />
      </Layout>
    </>
  )
}
